import os

REGISTER_TITLE_URL = os.environ['DIGITAL_REGISTER_URL']
USERNAME = os.environ['SMOKE_USERNAME']
PASSWORD = os.environ['SMOKE_PASSWORD']
TITLE_NUMBER = os.environ['DN1000']
PARTIAL_ADDRESS = os.environ['fake street']
POSTCODE = os.environ['PL9 9NB']

CONFIG_DICT = {
    'REGISTER_TITLE_URL': REGISTER_TITLE_URL,
    'USERNAME': USERNAME,
    'PASSWORD': PASSWORD,
    'TITLE_NUMBER': TITLE_NUMBER,
    'PARTIAL_ADDRESS': PARTIAL_ADDRESS,
    'POSTCODE': POSTCODE,
}
