source 'https://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'poltergeist'
gem 'pg'
gem 'rspec'
gem 'cucumber-repeat'
gem 'erubis'
gem 'rubocop'
gem 'w3c_validators'

group :development do
  gem 'pry'
end